from django.utils import timezone
from datetime import date, datetime
from django.db import models

# creates dyamic set of choices for founded date
YEAR_CHOICES = []
for r in range(2010, (datetime.now().year+1)):
        YEAR_CHOICES.append((r,r))

# creates a set of choices for funding units, k for 1 000, m for 1,000,000 etc
UNIT_CHOICES = ('','K','M','B')

class Company (models.Model):
# name of startup
    name = models.CharField(max_length=200, default=False)
# short description of busniess model
    description = models.CharField(max_length=2000, default='No description available')
# what year the company launched
    founded_year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.now().year)
# names of founders seperated by commas e.g ('Kevin Chan, Anmol Singh')
    founders = models.CharField(max_length=200,default=False)
# current startup's funding stage e.g ('Series A, Incubation.')
    stage = models.CharField(max_length=200,default=False)
# date of submission, generated by the django app
    submission_date = models.DateTimeField(default=timezone.now)
# industries/sectors business operates in seperated by commas e.g{'Fintech, Agriculture')
    industries = models.CharField(max_length=200,default=False)
# url to company's website
    website = models.URLField(max_length=200,default=False)
# contact email for the company
    email = models.EmailField(max_length=200,default=False)
# logo in the form of png or jpeg
    logo = models.ImageField(upload_to='logos',default="logos/undefined.png")
# amount of funding recieved
    funding = models.PositiveSmallIntegerField(default=False)
# the units of funding
    funding_unit = models.CharField(max_length=1,default=False)
